import { Footer, Navbar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'MyCar Car-showcase App by Nehal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-[100vw] overflow-x-hidden'>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
